
default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: cda_prod
  username: postgres
  password: developer

development:
  <<: *default

test:
  <<: *default
  database: cda_test 

#
production:
  <<: *default
  database: cda_production
  username: postgres
  password: developer
