
default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost 

development:
  <<: *default
  database: alfarero_development
  username: postgres
  password: developer

test:
  <<: *default
  database: alfarero_test 

#
production:
  <<: *default
  database: alfarero_production
  username: rails 
  password: XqvKcvJbEW 
