
default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: cda_prod

development:
  <<: *default 
  username: postgres
  password: developer

test:
  <<: *default
  database: cda_test 

production:
  <<: *default
  database: alfarero_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
