
default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: cda_prod
  username: postgres
  password: developer

development:
  <<: *default

test:
  <<: *default
  database: cda_test 

#
production:
  <<: *default
  database: dcrirfdansb5b5
  username: iztccbtmhvwkek
  password: T9gmk3I4FR2SbvxNEDWEUkZ91B
